# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0021_auto_20151223_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquerandomnumbersgroup',
            name='uniqueRandomNumbersCount',
            field=models.PositiveIntegerField(default=1, verbose_name=b'uniqueRandomNumbersCount'),
            preserve_default=False,
        ),
    ]
