# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0022_uniquerandomnumbersgroup_uniquerandomnumberscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueRandomNumbersGroup',
            new_name='UniqueRandomNumbers',
        ),
        migrations.RenameField(
            model_name='uniquerandomnumber',
            old_name='uniqueRandomNumbersGroup',
            new_name='uniqueRandomNumbers',
        ),
    ]
