# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0023_auto_20160104_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquerandomnumbers',
            name='uniqueRandomNumbersCount',
        ),
        migrations.AddField(
            model_name='uniquerandomnumbers',
            name='count',
            field=models.PositiveIntegerField(default=5000, verbose_name=b'count'),
            preserve_default=False,
        ),
    ]
